services:
  dev:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    volumes:
      - ./todo_app:/todo-app/todo_app
    env_file:
      - ./.env
    

  prod:
    build:
      context: .
      target: production
    ports:
      - "8000:5000"
    env_file:
      - ./.env

    