name: Continuous Integration 
on: [push] 
jobs: 
 build: 
  name: build
  runs-on: ubuntu-latest 
  steps: 
  - uses: actions/checkout@v2 
  - run: docker build --target test --tag todo-app:test .
  - run: docker run --env-file ./.env.test todo-app:test
 deploy:
  name: deploy
  needs: build
  runs-on: ubuntu-latest
  if: github.event_name == 'push'
  steps:
   - uses: actions/checkout@v2
   - run: docker login -u keithleverton -p ${{secrets.DOCKERPASSWORD}}
   - run: docker build --target production --tag keithleverton/todo-app:$GITHUB_SHA --tag keithleverton/todo-app .
   - run: docker push keithleverton/todo-app:$GITHUB_SHA
   - run: docker push keithleverton/todo-app
   - run: curl -dH --fail -X post ${{secrets.Webhook}}



