name: Continuous Integration 
on: [push] 
jobs: 
 build: 
  name: Build and test 
  runs-on: ubuntu-latest 
  steps: 
  - uses: actions/checkout@v2 
  - run: docker build --target test --tag todo-app:test .
  - run: docker run --env-file ./.env.test todo-app:test
 deploy:
 on:
  push:
    branches:
    - main
    - 'Module8'
 needs: Build and test
 jobs:
  - run: echo 'cd'

